apiVersion: v1
kind: Pod
metadata:
   name: simple-pod-enviroment-<your_name>
   namespace: <correct-namespace>
spec:
  containers:
     - name: simple-pod-container-enviroment
       image: busybox
       command: ["sh" , "-c", "echo My name is $NAME and my  surname is $SURNAME  && sleep $TIME_TO_COMPLETED"]
       env:
        - name : NAME
          value: "Alvaro"
