apiVersion: v1
kind: Pod
metadata:
   name: simple-pod-secrets-<your-name>
   namespace: <Correct-name-space>
spec:
  containers:
     - name: simple-pod-secrets-container-enviroment
       image: busybox
       command: ["sh" , "-c", "echo My name is $NAME and my  surname is $SURNAME and this is my secret $SECRET  && sleep $TIME_TO_COMPLETED"]
       #Enviroment variable  TIME_TO_COMPLETED is configured in Configuration file you need to  create it and store in k8s
       #Enviroment variable NAME SURNAME is mapping in cofigurations file you need to create  it and store in k8s 
       #Enviroment variable SECRET  is mapping in a secret file you need to  create it and store in k8s
       #Complete this file linking to ConfigMap Variable and Secrets variables
       #Run pod and show log

       # Kubectl instructions
         #kubectl get pods -n <namespaces>
         #kubectl describe pod <pod-name> -n <namespace>
         #kubectl get pod <pod-name> -o yaml export ><localfile>
         #kubectl apply -f <descriptor-file>
         #Kubectl delete pod <pod-name> -n namespace
         #Kubectl logs  <pod-name> -n <namespace>
