apiVersion: v1
kind: Pod
metadata:
   name: simple-pod-secrets-<your-name>
   namespace: microservices
spec:
  containers:
     - name: simple-pod-secrets-container-enviroment
       image: busybox
       command: ["sh" , "-c", "echo My name is $NAME and my  surname is $SURNAME and this is my secret $SECRET  && sleep $TIME_TO_COMPLETED"]
       #Enviroment variable  TIME_TO_COMPLETED is configured in POD
       #Enviroment variable NAME SURNAME is mapping in cofigurations file
       #Enviroment variable SECRET  is mapping in a secret file
